name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'CaidoExtension/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'CaidoExtension/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

# Remove working directory default since we're already in CaidoExtension folder

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Build extension
        run: pnpm build

      - name: Verify build
        run: |
          if [ ! -f "dist/plugin_package.zip" ]; then
            echo "Build failed: plugin_package.zip not found"
            exit 1
          fi
          
          # Verify manifest.json exists and is valid
          if ! unzip -p dist/plugin_package.zip manifest.json | jq . > /dev/null 2>&1; then
            echo "Invalid or missing manifest.json"
            exit 1
          fi
          
          VERSION=$(unzip -p dist/plugin_package.zip manifest.json | jq -r .version)
          echo "Extension version: ${VERSION}"
          echo "Build verification passed"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jshunter-caido-extension-${{ github.sha }}
          path: dist/plugin_package.zip
          retention-days: 7 