name: Release JSHunter Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build plugin
        run: pnpm build

      - name: Prepare release
        working-directory: dist
        run: |
          cp plugin_package.zip JSHunter-Plugin.zip
          sha256sum JSHunter-Plugin.zip > JSHunter-Plugin.zip.sha256
          ls -la

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest
          body: |
            ## JSHunter Caido Plugin - Latest Build
            
            **Commit:** ${{ github.sha }}
            **Date:** ${{ github.event.head_commit.timestamp }}
            
            ### Installation
            1. Download `JSHunter-Plugin.zip`
            2. Open Caido → Settings → Plugins
            3. Install the downloaded ZIP file
            4. Restart Caido
            
            ### Files
            - `JSHunter-Plugin.zip` - Main plugin package
            - `JSHunter-Plugin.zip.sha256` - SHA256 checksum
          artifacts: |
            dist/JSHunter-Plugin.zip
            dist/JSHunter-Plugin.zip.sha256
          allowUpdates: true
          removeArtifacts: true
          makeLatest: true 